
server:
  port: 10087
  max-http-header-size: 10240


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 111111
    filters: wall,mergeStat
  application:
    name: zhima
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    enabled: false


mybatis:
  mapper-locations: "classpath:com.zyt.zhima.mapper/*.xml"
  type-aliases-package: com.zyt.zhima.model

mapper:
    mappers:
        - com.zyt.zhima.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  config: "classpath:logback-spring.xml"
  file: "./logs/zhima-log.log"


zhima:
  image_server: http://47.103.87.87:9090/